/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test.jframe;

import entity.User;

/**
 *
 * @author ADMIN
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    User user;
    public MainFrame(User user) {
        this.user = user;
        initComponents();
        Jmenu_user.setText("Chào "+this.user.getHoTen());
        if(user.getRole().equals("nhanvien")){
            jMenuItem_NhanVien.setEnabled(false);
            jMenuItem_phong.setEnabled(false);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jMenu1 = new javax.swing.JMenu();
        popupMenu1 = new java.awt.PopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_Phim = new javax.swing.JMenuItem();
        jMenuItem_phong = new javax.swing.JMenuItem();
        jMenuItem_Lich = new javax.swing.JMenuItem();
        jMenuItem_NhanVien = new javax.swing.JMenuItem();
        Jmenu_user = new javax.swing.JMenu();
        jMenuItem_logout = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jMenuItem1.setText("jMenuItem1");

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        jMenu1.setText("jMenu1");

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        label1.setText("label1");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );

        jMenu4.setText("Quản lí...");

        jMenuItem_Phim.setText("Phim");
        jMenuItem_Phim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PhimActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_Phim);

        jMenuItem_phong.setText("Phòng");
        jMenuItem_phong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_phongActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_phong);

        jMenuItem_Lich.setText("Lịch chiếu");
        jMenuItem_Lich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LichActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_Lich);

        jMenuItem_NhanVien.setText("Nhân viên");
        jMenuItem_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NhanVienActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_NhanVien);

        jMenuBar1.add(jMenu4);

        Jmenu_user.setLabel("Chào");

        jMenuItem_logout.setLabel("Đăng xuất");
        jMenuItem_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_logoutActionPerformed(evt);
            }
        });
        Jmenu_user.add(jMenuItem_logout);

        jMenuBar1.add(Jmenu_user);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 97, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_PhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PhimActionPerformed
        // TODO add your handling code here:
        label1.setText("Quản lý Phim");
    }//GEN-LAST:event_jMenuItem_PhimActionPerformed

    private void jMenuItem_LichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LichActionPerformed
        // TODO add your handling code here:
        label1.setText("Quản lý Lịch");
    }//GEN-LAST:event_jMenuItem_LichActionPerformed

    private void jMenuItem_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NhanVienActionPerformed
        // TODO add your handling code here:
        label1.setText("Quản lý Nhân viên");
    }//GEN-LAST:event_jMenuItem_NhanVienActionPerformed

    private void jMenuItem_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_logoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem_logoutActionPerformed

    private void jMenuItem_phongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_phongActionPerformed
        // TODO add your handling code here:
        label1.setText("Quản lý Phòng");
    }//GEN-LAST:event_jMenuItem_phongActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Jmenu_user;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem_Lich;
    private javax.swing.JMenuItem jMenuItem_NhanVien;
    private javax.swing.JMenuItem jMenuItem_Phim;
    private javax.swing.JMenuItem jMenuItem_logout;
    private javax.swing.JMenuItem jMenuItem_phong;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private java.awt.Label label1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.Panel panel1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    // End of variables declaration//GEN-END:variables
}
